# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'VideoBalance' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoBalance
  pod 'Alamofire', '~> 5.0.0-beta.3'
  pod 'Player', '~> 0.13.0'
  pod 'Zip', '~> 1.1'

  target 'VideoBalanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
